### ISSUE TITLE
Failing Test - zipwith

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/ramda#2]
There's a failing test. Follow the guide in the readme and run the tests to find out what the error is.

**Comment by RaghuChandrasekaran** [comment]
I'd like to work on this one.

**Comment by CraigRodrigues** [comment]
I'll take a shot at this.

**Comment by dfrownfelter** [comment]
Good luck!

**Comment by paulwithap** [comment]
Dammit! I should have commented sooner. I fixed the bug first instead :/

**Comment by dfrownfelter** [comment]
@paulwithap There's still some good bugs! Check out the [redux](https://github.com/firstpr/redux) repo. I think it's a good one.
