### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/ramda#2]
There is a failing test that needs to be fixed.

Follow the guide [here](http://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/) to get started. When the project in on your machine, run `npm install` and then `npm test`. Good luck!

**Comment by rstefanic** [comment]
I would love to take this. May I do it?

**Comment by dfrownfelter** [comment]
Go for it! It's yours. Also let me know if you have any issues.

**Comment by rstefanic** [comment]
Great. Thanks. I'll let you know if I run into any issues. I appreciate you setting this up.

**Comment by dfrownfelter** [comment]
No problem, have fun!

**Comment by dfrownfelter** [comment]
@rstefanic we changed the name of the organization, so you have to update your remote. Run `git remote set-url upstream https://github.com/firstpr/yarn.git` to change it.
